"""P4 calculation constants."""

CALCULATION_VERSION = "P4_MVP_1.0"
UNIVERSE_SCOPE = "LOADED_A_SHARE_SAMPLE"
UNIVERSE_STATUS = "PARTIAL_UNIVERSE"
CORE_WINDOWS = (5, 20, 60)
DEFAULT_LOOKBACK = 60
MAX_LOOKBACK = 250
