"""Transparent P6 calculation constants."""

CALCULATION_VERSION = "P6_SECTOR_MVP_V1"
SECTOR_SYSTEM = "SW"
SECTOR_LEVEL = 1
BENCHMARK_CODE = "000300"
BENCHMARK_EXCHANGE = "SSE"
BENCHMARK_NAME = "沪深300"
RANK_CHANGE_THRESHOLD = 3
MAX_LOOKBACK = 500
