"""Frozen V1.0 constants for the transparent Market Regime Engine."""

CALCULATION_VERSION = "MARKET_REGIME_V1.0"
MA_WINDOWS = (5, 20, 60)
INDEX_WEIGHT = 0.50
BREADTH_WEIGHT = 0.50
MIN_VALID_CORE_INDICES = 5
MIN_BREADTH_ELIGIBLE_RATIO = 0.80
MAX_HISTORY_LOOKBACK = 250
DEFAULT_HISTORY_LOOKBACK = 120

STATE_LABELS = {
    "STRONG": "强势",
    "MODERATELY_STRONG": "偏强",
    "RANGE_BOUND": "震荡",
    "MODERATELY_WEAK": "偏弱",
    "WEAK": "弱势",
    "INSUFFICIENT_DATA": "数据不足",
}

STRATEGY_EFFECT = "CONTEXT_ONLY_DOES_NOT_CHANGE_STRATEGY1"
DISCLAIMER = "市场环境分类不是走势预测、策略推荐或买卖建议。"
